#################################################################
# config.yml の文字コードは Shift_JIS を使用(日本語表記のため)
# コンソールに WARN(警告) が表示されるが CraftBukkit の仕様です
# プラグイン自体は正常に動作します
#################################################################

# 経験値 1 に対する購入額
exp-buy-rate: 1.0

# 経験値 1 に対する売却額
exp-sell-rate: 1.0

# コンソールに色付き文字を表示
color-logs: true

# コンソールにデバッグを表示
debug-mode: false

# ゲーム内メッセージの言語ファイル
language-file: lang-jp.yml
