name: NepianEXP
main: nepian.bukkit.plugin.exp.Main
version: 1.1.1
author: Nepian
depend:
- Vault
commands:
  exp:
    aliases:
    - nexp
permissions:
  nepian.exp.public:
    default: true
    children:
      nepian.exp: true
      nepian.exp.help: true
      nepian.exp.info: true
      nepian.exp.buy: true
      nepian.exp.sell: true
      nepian.exp.send: true

  nepian.exp.config.*:
    children:
      nepian.exp.config: true
      nepian.exp.config.reload: true

  nepian.exp.op:
    default: op
    children:
      nepian.exp.public: true
      nepian.exp.info.player: true
      nepian.exp.reload: true
      nepian.exp.add: true
      nepian.exp.add.player: true
      nepian.exp.set: true
      nepian.exp.set.player: true
      nepian.exp.reset: true
      nepian.exp.config.*: true